# Setup
title: Nathanael Seen's
tagline: Knowledge Wiki
url: https://www.nathanaelseen.com
paginate: 1
baseurl: ""
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      permalink: /:basename

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

include: [_pages]

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# For math-jax (math notations)
markdown: Kramdown

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-165726081-1

# Specify the author for blog posts
author:
  name: Nathanael Seen
  url: https://twitter.com/mdo
  email: coderatwork64@gmail.com


# Custom vars
version: 3.0.0
